"""Named constants used across the fitness tracker domain."""
import re

# Time units
DAYS_PER_WEEK = 7
DAYS_PER_MONTH = 30
SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
SECONDS_PER_HOUR = 3600
PERCENT = 100.0

# Users and profiles
MIN_AGE_YEARS = 13
MAX_AGE_YEARS = 120
MIN_NAME_LENGTH = 2
MIN_PASSWORD_LENGTH = 8
PBKDF2_ITERATIONS = 100_000
EMAIL_PATTERN = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
GENDERS = ("male", "female")
DEFAULT_ACTIVITY_LEVEL = "moderate"
ACTIVITY_MULTIPLIERS = {
    "sedentary": 1.2,
    "light": 1.375,
    "moderate": 1.55,
    "active": 1.725,
    "extreme": 1.9,
}
CM_PER_METER = 100.0
MIN_HEIGHT_CM = 50.0
MAX_HEIGHT_CM = 260.0
MIN_WEIGHT_KG = 20.0
MAX_WEIGHT_KG = 400.0
MAX_BODY_FAT_PERCENT = 70.0

# Exercises and workouts
MUSCLE_GROUPS = ("chest", "back", "legs", "arms", "shoulders", "core", "full body")
MIN_DIFFICULTY = 1
MAX_DIFFICULTY = 5
MIN_REPS = 1
SECONDS_PER_REP = 3
EPLEY_DIVISOR = 30.0

# Cardio
RUNNING_MET = 9.8
CYCLING_MET = 7.5
SWIMMING_MET = 8.0
DEFAULT_MET = 5.0
KCAL_PER_MET_KG_HOUR = 1.05
METERS_PER_KM = 1000.0
EARTH_RADIUS_KM = 6371.0
MIN_LATITUDE = -90.0
MAX_LATITUDE = 90.0
MIN_LONGITUDE = -180.0
MAX_LONGITUDE = 180.0

# Health metrics
MIN_BPM = 30
MAX_BPM = 240
MAX_HEART_RATE_BASE = 220
HEART_RATE_ZONES = (
    ("warm-up", 0.5, 0.6),
    ("fat burn", 0.6, 0.7),
    ("cardio", 0.7, 0.85),
    ("peak", 0.85, 1.0),
)
DEFAULT_STEP_GOAL = 10_000
DEFAULT_STRIDE_M = 0.762
DEFAULT_HYDRATION_GOAL_ML = 2000
MIN_SLEEP_HOURS = 7.0
MAX_QUALITY_SCORE = 100
GOOD_SLEEP_QUALITY = 80
FAIR_SLEEP_QUALITY = 50

# Nutrition
MEAL_TYPES = ("breakfast", "lunch", "dinner", "snack")
KCAL_PER_GRAM_PROTEIN = 4.0
KCAL_PER_GRAM_CARBS = 4.0
KCAL_PER_GRAM_FAT = 9.0

# Energy balance and BMI
BMR_WEIGHT_COEFFICIENT = 10.0
BMR_HEIGHT_COEFFICIENT = 6.25
BMR_AGE_COEFFICIENT = 5.0
BMR_MALE_OFFSET = 5.0
BMR_FEMALE_OFFSET = -161.0
KCAL_PER_KG_FAT = 7700.0
BMI_UNDERWEIGHT_LIMIT = 18.5
BMI_NORMAL_LIMIT = 25.0
BMI_OVERWEIGHT_LIMIT = 30.0
TREND_THRESHOLD_PERCENT = 5.0

# Social
DEFAULT_MAX_PARTICIPANTS = 50
MAX_COMMENT_LENGTH = 280
MAX_POST_LENGTH = 500
DEFAULT_FEED_SIZE = 10

# Devices and notifications
FULL_BATTERY_PERCENT = 100
LOW_BATTERY_PERCENT = 20
SYNC_BATTERY_COST = 2
DEFAULT_SNOOZE_MINUTES = 10

# Subscriptions and coaching
PLAN_STATUS_SCHEDULED = "scheduled"
PLAN_STATUS_CONFIRMED = "confirmed"
PLAN_STATUS_CANCELLED = "cancelled"
PLAN_STATUS_COMPLETED = "completed"
